### ISSUE TITLE
Can't run eclipse checkstyle check from system not connected to internet.

### ISSUE THREAD

**Issue by mikeisgo** [checkstyle/eclipse-cs#114]
https://github.com/checkstyle/eclipse-cs/blob/768ef915f55231426e09afc63183761415e19ab7/net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/ConfigurationReader.java#L98

Attempting to run checkstyle on code, from a computer that is disconnected from the internet, fails at this point in the code.  I've found that if you have a web server on your localhost and import your own configuration XML with the dtd location changed to that localhost location where you've saved the dtd to, then the DTD is found and operates successfully. 

Stacktrace below:

```
net.sf.eclipsecs.core.util.CheckstylePluginException: Remote host closed connection during handshake Nested exception: Remote host closed connection during handshake
	at net.sf.eclipsecs.core.util.CheckstylePluginException.rethrow(CheckstylePluginException.java:67)
	at net.sf.eclipsecs.core.util.CheckstylePluginException.rethrow(CheckstylePluginException.java:80)
	at net.sf.eclipsecs.core.config.ConfigurationReader.read(ConfigurationReader.java:102)
	at net.sf.eclipsecs.core.config.ConfigurationReader.getAdditionalConfigData(ConfigurationReader.java:122)
	at net.sf.eclipsecs.core.builder.CheckerFactory.getAdditionalData(CheckerFactory.java:172)
	at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:145)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.handleBuildSelection(CheckstyleBuilder.java:306)
	at net.sf.eclipsecs.core.jobs.RunCheckstyleOnFilesJob.runInWorkspace(RunCheckstyleOnFilesJob.java:119)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
Caused by: org.dom4j.DocumentException: Remote host closed connection during handshake Nested exception: Remote host closed connection during handshake
	at org.dom4j.io.SAXReader.read(SAXReader.java:484)
	at net.sf.eclipsecs.core.config.ConfigurationReader.read(ConfigurationReader.java:98)
	... 7 more
```

**Comment by rnveach** [comment]
@mikeisgo What is the top portion of your configuration, which specifies the dtd, that eclipse-cs is using?

**Comment by mikeisgo** [comment]
I'm using the currently available 8.12.0 version downloadable from the Eclipse Marketplace, and the stacktrace i posted is from eclipse when it errors out.  I'm not compiling my own plugin, so I'd assume the  https://github.com/checkstyle/eclipse-cs/blob/master/net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/ConfigurationReader.java#L62-L73
link you provided is the top configuration used in that plugin.  I believe the 8.12.0 tag of the codebase shows that same list of DTDs.  I would assume the same thing that the locally provided DTDs are compiled into the plugin for the 1_3 version.  

The checks xml file I'm using prescribes the following:

```
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">
```

Which is from this file: https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml

**Comment by rnveach** [comment]
The DTD map in eclipse CS is not correct.

https://github.com/checkstyle/eclipse-cs/blob/master/net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/ConfigurationReader.java#L72
> -//Checkstyle//DTD Check Configuration 1.3//EN

This should be `-//Checkstyle//DTD Checkstyle Configuration 1.3//EN`. It is missing the 2nd `Checkstyle` and just have `Check` instead. This is why it is requiring internet connection to find the right DTD.

**Comment by slothquanta** [comment]
Have the fix been uploaded to the eclipse market place build? I just installed the 8.0.12 from Eclipse market place and had the same error here.

**Comment by rnveach** [comment]
Nothing has been released in almost 1 year for eclipse-cs.
