### ISSUE TITLE
eclipse-cs fails with spring-javaformat checkstyle

### ISSUE THREAD

**Issue by cirelli94** [checkstyle/eclipse-cs#217]
eclipse-cs fails with spring-javaformat checkstyle

I set up spring-javaformat plugin with Checkstyle.
When I run build it says:
```
Errors occurred during the build.
Errors running builder 'Checkstyle Builder' on project 'timebank-api'.
java.lang.NullPointerException
```

Attached there's the log.
Thanks in advance.
[Untitled.log](https://github.com/checkstyle/eclipse-cs/files/4280264/Untitled.log)

````
java.lang.NullPointerException
	at net.sf.eclipsecs.core.config.configtypes.ConfigurationType.getCheckstyleConfiguration(ConfigurationType.java:123)
	at net.sf.eclipsecs.core.config.CheckConfiguration.getCheckstyleConfiguration(CheckConfiguration.java:161)
	at net.sf.eclipsecs.core.builder.CheckerFactory.getCacheKey(CheckerFactory.java:171)
	at net.sf.eclipsecs.core.builder.CheckerFactory.createChecker(CheckerFactory.java:104)
	at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:140)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.handleBuildSelection(CheckstyleBuilder.java:307)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.build(CheckstyleBuilder.java:173)
````

https://github.com/checkstyle/eclipse-cs/blob/e8cc8d12fd96472a9b1cdbbdd8c5b02151a84a4a/net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/configtypes/ConfigurationType.java#L123

Some info about my environment:
Eclipse IDE for Java Developers Version: 2019-12 (4.14.0) Build id: 20191212-1212
Eclipse Checkstyle Project	Eclipse Checkstyle	8.29.0.202001290016	net.sf.eclipsecs

I attached Installation Details > Configuration in eclipse-configuration.txt file.

[eclipse-configuration.txt](https://github.com/checkstyle/eclipse-cs/files/4286154/eclipse-configuration.txt)

**Comment by Calixte** [comment]
This was a bug in spring-javaformat that was fixed by https://github.com/spring-io/spring-javaformat/pull/179.
