### ISSUE TITLE
 cannot initialize module TreeWalker - cannot initialize module FileContentsHolder - Unable to instantiate 

### ISSUE THREAD

**Issue by ashishsahuGitHub** [checkstyle/eclipse-cs#227]
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - cannot initialize module FileContentsHolder - Unable to instantiate 'FileContentsHolder' class, it is also not possible to instantiate it as com.puppycrawl.tools.checkstyle.checks.annotation.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.blocks.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.coding.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.design.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.header.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.imports.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.indentation.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.javadoc.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.metrics.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.modifier.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.naming.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.regexp.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.sizes.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.whitespace.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.FileContentsHolder, com.puppycrawl.tools.checkstyle.filefilters.FileContentsHolder, com.puppycrawl.tools.checkstyle.filters.FileContentsHolder, com.puppycrawl.tools.checkstyle.FileContentsHolder, FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.annotation.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.blocks.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.coding.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.design.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.header.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.imports.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.indentation.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.javadoc.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.metrics.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.modifier.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.naming.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.regexp.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.sizes.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.whitespace.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.filefilters.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.filters.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.FileContentsHolderCheck. Please recheck that class name is specified as canonical name or read how to configure short name usage https://checkstyle.org/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:473)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
	at net.sf.eclipsecs.core.builder.CheckerFactory.createCheckerInternal(CheckerFactory.java:240)
	at net.sf.eclipsecs.core.builder.CheckerFactory.createChecker(CheckerFactory.java:122)
	at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:139)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.handleBuildSelection(CheckstyleBuilder.java:307)
	at net.sf.eclipsecs.core.jobs.RunCheckstyleOnFilesJob.runInWorkspace(RunCheckstyleOnFilesJob.java:119)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module FileContentsHolder - Unable to instantiate 'FileContentsHolder' class, it is also not possible to instantiate it as com.puppycrawl.tools.checkstyle.checks.annotation.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.blocks.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.coding.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.design.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.header.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.imports.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.indentation.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.javadoc.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.metrics.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.modifier.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.naming.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.regexp.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.sizes.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.whitespace.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.FileContentsHolder, com.puppycrawl.tools.checkstyle.filefilters.FileContentsHolder, com.puppycrawl.tools.checkstyle.filters.FileContentsHolder, com.puppycrawl.tools.checkstyle.FileContentsHolder, FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.annotation.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.blocks.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.coding.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.design.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.header.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.imports.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.indentation.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.javadoc.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.metrics.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.modifier.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.naming.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.regexp.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.sizes.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.whitespace.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.filefilters.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.filters.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.FileContentsHolderCheck. Please recheck that class name is specified as canonical name or read how to configure short name usage https://checkstyle.org/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:123)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:468)
	... 8 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to instantiate 'FileContentsHolder' class, it is also not possible to instantiate it as com.puppycrawl.tools.checkstyle.checks.annotation.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.blocks.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.coding.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.design.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.header.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.imports.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.indentation.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.javadoc.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.metrics.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.modifier.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.naming.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.regexp.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.sizes.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.whitespace.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.FileContentsHolder, com.puppycrawl.tools.checkstyle.filefilters.FileContentsHolder, com.puppycrawl.tools.checkstyle.filters.FileContentsHolder, com.puppycrawl.tools.checkstyle.FileContentsHolder, FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.annotation.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.blocks.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.coding.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.design.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.header.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.imports.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.indentation.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.javadoc.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.metrics.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.modifier.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.naming.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.regexp.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.sizes.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.whitespace.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.filefilters.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.filters.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.FileContentsHolderCheck. Please recheck that class name is specified as canonical name or read how to configure short name usage https://checkstyle.org/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
	at com.puppycrawl.tools.checkstyle.PackageObjectFactory.createModule(PackageObjectFactory.java:211)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:114)
	... 10 more

Help me to solve this 
Thanks In advance

**Comment by rnveach** [comment]
FileContentsHolder was removed in https://checkstyle.org/releasenotes.html#Release_8.2 . You will have to remove the module to use newer versions of Checkstyle.

**Comment by ashishsahuGitHub** [comment]
Thanks
