### ISSUE TITLE
[Question] Eclipse: How to  find suppressions xml if it is in a jar dependency

### ISSUE THREAD

**Issue by space88man** [checkstyle/eclipse-cs#268]
Question: any idea why the checkstyle plugin in Eclipse cannot find the second file (a file= reference to suppressions) on the class path?

Using Eclipse + JBoss Tools  on the https://github.com/wildfly/quickstart examples.

The checkstyle config that this code base uses is in a separate jar: https://github.com/wildfly/wildfly-checkstyle-config

The main checkstyle file is referenced as 

```
# eclipse-cs manages to find this file inside the jar
                    <configuration>
                        <configLocation>/wildfly-checkstyle/checkstyle.xml</configLocation>
                        <includeTestSourceDirectory>true</includeTestSourceDirectory>
                        <sourceDirectories>
                            <directory>${project.build.sourceDirectory}</directory>
                        </sourceDirectories>
                        <resourceIncludes>**/*.properties,**/*.xml</resourceIncludes>
                        <includeTestResources>true</includeTestResources>
                        <includeResources>true</includeResources>
                        <consoleOutput>true</consoleOutput>
                        <failsOnError>true</failsOnError>
                        <failOnViolation>true</failOnViolation>
                    </configuration>

# dependency
                        <dependency>
                            <groupId>org.wildfly.checkstyle</groupId>
                            <artifactId>wildfly-checkstyle-config</artifactId>
                            <version>1.0.8.Final</version>
                        </dependency>

```

Inside this config file, suppression config is located as 
```
    <module name="SuppressionFilter">
        <property name="file" value="/wildfly-checkstyle/suppressions.xml" />
    </module>
```

However, when running, the Checkstyle plugin shows the following error:
```
# Unfortunately cannot find /wildfly-checkstyle/suppressions.xml in the class path
eclipse.buildId=4.17.0.I20200902-1800
java.version=11.0.8
java.vendor=Red Hat, Inc.
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_SG
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.jee.product

net.sf.eclipsecs.core
Error
Sat Sep 26 22:50:38 SGT 2020
Checkstyle-Plugin: cannot initialize module SuppressionFilter - Unable to find: /wildfly-checkstyle/suppressions.xml

com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module SuppressionFilter - Unable to find: /wildfly-checkstyle/suppressions.xml
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:482)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
	at net.sf.eclipsecs.core.builder.CheckerFactory.createCheckerInternal(CheckerFactory.java:240)
	at net.sf.eclipsecs.core.builder.CheckerFactory.createChecker(CheckerFactory.java:122)
	at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:139)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.handleBuildSelection(CheckstyleBuilder.java:307)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.build(CheckstyleBuilder.java:173)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:832)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to find: /wildfly-checkstyle/suppressions.xml
	at com.puppycrawl.tools.checkstyle.utils.CommonUtil.getUriByFilename(CommonUtil.java:527)
	at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader.loadSuppressions(SuppressionsLoader.java:222)
	at com.puppycrawl.tools.checkstyle.filters.SuppressionFilter.finishLocalSetup(SuppressionFilter.java:274)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:197)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:477)
	... 18 more

```

When `mvn clean checkstyle:checkstyle` is run on the command line, it doesn't show any error, so it would seem that `/wildfly-checkstyle/suppressions.xml` is found correctly.

**Comment by space88man** [comment]
Ok — this is weird — the problem seems to have resolved by itself, and I no longer get Checkstyle plugin errors.
