### ISSUE TITLE
Checkstyle chokes on module-info.java

### ISSUE THREAD

**Issue by Brixomatic** [checkstyle/eclipse-cs#359]
Setup:
* Using Eclipse 2022-06, build 20220609-1112
* SpotBugs Project	SpotBugs	4.7.1.r202206270833-c133f55	com.github.spotbugs.plugin.eclipse
* Eclipse Checkstyle Project	Eclipse Checkstyle	10.0.0.202205010451	net.sf.eclipsecs

Simple project using com.github.spotbugs.annotations, declaring a module-info.java file and using one of the annotations, like so:
(It compiles fine using Maven and Eclipse)
```java
module some.random.project.core {
  exports some.random.project.core ;
  opens some.random.project.core.model to someone.else;
  
  requires transitive java.desktop; // also needed to use this lib
  requires net.sourceforge.argparse4j; 
 
  requires static com.github.spotbugs.annotations; // needed for checkstyle/spotbugs
  requires static jsr305; // optional, only used for compilation, not at runtime
}
```
Exception from error.log:

```js
plugin net.sf.eclipsecs.core:
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing C:\Users\XXX\git\PROJECT\src\main\java\module-info.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:305)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:224)
	at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:146)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.handleBuildSelection(CheckstyleBuilder.java:307)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.build(CheckstyleBuilder.java:173)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1024)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:254)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:311)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:400)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:403)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:514)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:462)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:544)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:161)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:255)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: IllegalStateException occurred while parsing file C:\Users\XXX\git\PROJECT\src\main\java\module-info.java.
	at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:105)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:152)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:331)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:292)
	... 17 more
Caused by: java.lang.IllegalStateException: 1:0: no viable alternative at input 'module'
	at com.puppycrawl.tools.checkstyle.JavaParser$CheckstyleErrorListener.syntaxError(JavaParser.java:252)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:310)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:136)
	at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.compilationUnit(JavaLanguageParser.java:424)
	at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:99)
	... 21 more
Caused by: org.antlr.v4.runtime.NoViableAltException
	at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:2028)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:467)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:393)
	at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.compilationUnit(JavaLanguageParser.java:380)
	... 22 more
```

Only workaround I know is to add an ExclusionFileFilter to the checkstyle.xml like so:
```xml
  <module name="BeforeExecutionExclusionFileFilter">
    <property name="fileNamePattern" value=".*(Example|Test|module-info)(\$.*)?"/>
  </module>
```

**Comment by rnveach** [comment]
This is a known Checkstyle issue. See https://github.com/checkstyle/checkstyle/issues/8240 .

I don't think there is much eclipse-cs can do since Checkstyle has to implement the support.

> Only workaround I know is to add an ExclusionFileFilter 

That is the correct work around recommended by Checkstyle.

**Comment by Brixomatic** [comment]
Closing issue (deferred/duplicate).
