### ISSUE TITLE
creating new config blocks main thread

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/eclipse-cs#375]
Creating a new configuration from the preference page leads to blocking the main thread for several seconds. That operation should be run via a UI job to avoid "application not responding".

**Comment by rnveach** [comment]
This also shows up in the Error Log view. I assume this fix has not been released yet.

![ui freeze](https://user-images.githubusercontent.com/5427943/216506859-5772a402-b33f-4ae3-ac5a-06bba2e5f9cd.png)

One of the freeze items has Metadata in the log:
````
Stack Trace
	at javassist.bytecode.CodeAttribute.<init>(CodeAttribute.java:102)
	at javassist.bytecode.AttributeInfo.read(AttributeInfo.java:87)
	at javassist.bytecode.MethodInfo.read(MethodInfo.java:568)
	at javassist.bytecode.MethodInfo.<init>(MethodInfo.java:109)
	at javassist.bytecode.ClassFile.read(ClassFile.java:817)
	at javassist.bytecode.ClassFile.<init>(ClassFile.java:185)
	at org.reflections.Reflections.getClassFile(Reflections.java:232)
	at org.reflections.Reflections.lambda$scan$2(Reflections.java:185)
....
	at org.reflections.Reflections.scan(Reflections.java:173)
	at org.reflections.Reflections.<init>(Reflections.java:126)
	at org.reflections.Reflections.<init>(Reflections.java:159)
	at org.reflections.Reflections.<init>(Reflections.java:151)
	at net.sf.eclipsecs.core.config.meta.MetadataFactory.loadThirdPartyModuleExtensionMetadata(MetadataFactory.java:160)
	at net.sf.eclipsecs.core.config.meta.MetadataFactory.doInitialization(MetadataFactory.java:563)
	at net.sf.eclipsecs.core.config.meta.MetadataFactory.refresh(MetadataFactory.java:544)
	at net.sf.eclipsecs.core.config.meta.MetadataFactory.<clinit>(MetadataFactory.java:149)
````
