### ISSUE TITLE
(8.7 regression) CheckstyleException: cannot initialize module TreeWalker

### ISSUE THREAD

**Issue by Maia-Everett** [checkstyle/eclipse-cs#44]
This seems to be a regression with 8.7. In a multi-project workspace, the Checkstyle plugin fails to work for one project while working for the others.

```
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Unable to instantiate 'FileContentsHolder' class, it is also not possible to instantiate it as com.puppycrawl.tools.checkstyle.checks.annotation.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.blocks.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.coding.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.design.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.header.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.imports.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.indentation.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.javadoc.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.metrics.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.modifier.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.naming.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.regexp.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.sizes.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.whitespace.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.FileContentsHolder, com.puppycrawl.tools.checkstyle.filefilters.FileContentsHolder, com.puppycrawl.tools.checkstyle.filters.FileContentsHolder, com.puppycrawl.tools.checkstyle.FileContentsHolder, FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.annotation.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.blocks.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.coding.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.design.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.header.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.imports.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.indentation.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.javadoc.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.metrics.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.modifier.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.naming.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.regexp.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.sizes.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.whitespace.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.filefilters.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.filters.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.FileContentsHolderCheck. Please recheck that class name is specified as canonical name or read how to configure short name usage http://checkstyle.sourceforge.net/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:464)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:197)
	at net.sf.eclipsecs.core.builder.CheckerFactory.createCheckerInternal(CheckerFactory.java:299)
	at net.sf.eclipsecs.core.builder.CheckerFactory.createChecker(CheckerFactory.java:133)
	at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:141)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.handleBuildSelection(CheckstyleBuilder.java:306)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.build(CheckstyleBuilder.java:172)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to instantiate 'FileContentsHolder' class, it is also not possible to instantiate it as com.puppycrawl.tools.checkstyle.checks.annotation.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.blocks.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.coding.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.design.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.header.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.imports.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.indentation.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.javadoc.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.metrics.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.modifier.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.naming.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.regexp.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.sizes.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.whitespace.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.FileContentsHolder, com.puppycrawl.tools.checkstyle.filefilters.FileContentsHolder, com.puppycrawl.tools.checkstyle.filters.FileContentsHolder, com.puppycrawl.tools.checkstyle.FileContentsHolder, FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.annotation.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.blocks.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.coding.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.design.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.header.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.imports.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.indentation.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.javadoc.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.metrics.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.modifier.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.naming.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.regexp.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.sizes.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.whitespace.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.filefilters.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.filters.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.FileContentsHolderCheck. Please recheck that class name is specified as canonical name or read how to configure short name usage http://checkstyle.sourceforge.net/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
	at com.puppycrawl.tools.checkstyle.PackageObjectFactory.createModule(PackageObjectFactory.java:208)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:166)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:197)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:459)
	... 18 more
```

**Comment by lkoe** [comment]
The module `FileContentsHolder` has been removed from Checkstyle core a while ago (http://checkstyle.sourceforge.net/releasenotes.html#Release_8.2). It seems on of your configurations is still referring to it. To fix the problem please update the Checkstyle configuration in question.

**Comment by Maia-Everett** [comment]
That fixed it for me, thanks. Would prefer a more intelligible error message, though, as I'd imagine there are lots of people migrating old configuration files who would find this error message confusing.

**Comment by lkoe** [comment]
Given the regular support questions about this, I feel you're right. :-)
However, the error message is generated by Checkstyle core. Please request improvements there (https://github.com/checkstyle/checkstyle).
