### ISSUE TITLE
Checkstyle-Plugin 8.5.1 does not work with Eclipse Oxygen 4.7.2

### ISSUE THREAD

**Issue by AlBundy33** [checkstyle/eclipse-cs#5]
Installed:   Eclipse Checkstyle Plug-in	8.5.1.201712211522	net.sf.eclipsecs.feature.group	http://eclipse-cs.sf.net/

Eclipse shows only:  Checkstyle execution failed due to an internal error. Please check the error log for details...

Logfiles says:
<pre>
!ENTRY net.sf.eclipsecs.core 4 0 2018-01-09 17:04:24.035
!MESSAGE Checkstyle-Plugin: cannot initialize module TreeWalker - Fehler beim Instanziieren der Klasse 'FileContentsHolder'. Es war auch nicht möglich, sie als com.puppycrawl.tools.checkstyle.checks.annotation.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.blocks.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.coding.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.design.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.header.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.imports.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.indentation.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.javadoc.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.metrics.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.modifier.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.naming.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.regexp.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.sizes.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.whitespace.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.FileContentsHolder, com.puppycrawl.tools.checkstyle.filefilters.FileContentsHolder, com.puppycrawl.tools.checkstyle.filters.FileContentsHolder, com.puppycrawl.tools.checkstyle.FileContentsHolder, FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.annotation.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.blocks.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.coding.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.design.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.header.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.imports.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.indentation.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.javadoc.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.metrics.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.modifier.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.naming.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.regexp.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.sizes.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.whitespace.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.filefilters.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.filters.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.FileContentsHolderCheck zu instanziieren. Bitte prüfen Sie, dass der Klassenname als kanonischer Name angegeben wurde oder lesen Sie, wie Sie abgekürzte Namen konfigurieren: http://checkstyle.sourceforge.net/config.html#Packages. Bitte prüfen Sie auch, dass der angegebene ClassLoader des Checkers richtig konfiguriert ist.
!STACK 0
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Fehler beim Instanziieren der Klasse 'FileContentsHolder'. Es war auch nicht möglich, sie als com.puppycrawl.tools.checkstyle.checks.annotation.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.blocks.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.coding.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.design.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.header.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.imports.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.indentation.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.javadoc.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.metrics.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.modifier.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.naming.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.regexp.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.sizes.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.whitespace.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.FileContentsHolder, com.puppycrawl.tools.checkstyle.filefilters.FileContentsHolder, com.puppycrawl.tools.checkstyle.filters.FileContentsHolder, com.puppycrawl.tools.checkstyle.FileContentsHolder, FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.annotation.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.blocks.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.coding.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.design.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.header.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.imports.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.indentation.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.javadoc.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.metrics.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.modifier.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.naming.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.regexp.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.sizes.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.whitespace.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.filefilters.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.filters.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.FileContentsHolderCheck zu instanziieren. Bitte prüfen Sie, dass der Klassenname als kanonischer Name angegeben wurde oder lesen Sie, wie Sie abgekürzte Namen konfigurieren: http://checkstyle.sourceforge.net/config.html#Packages. Bitte prüfen Sie auch, dass der angegebene ClassLoader des Checkers richtig konfiguriert ist.
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:464)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:186)
	at net.sf.eclipsecs.core.builder.CheckerFactory.createCheckerInternal(CheckerFactory.java:299)
	at net.sf.eclipsecs.core.builder.CheckerFactory.createChecker(CheckerFactory.java:133)
	at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:141)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.handleBuildSelection(CheckstyleBuilder.java:306)
	at net.sf.eclipsecs.core.jobs.RunCheckstyleOnFilesJob.runInWorkspace(RunCheckstyleOnFilesJob.java:119)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Fehler beim Instanziieren der Klasse 'FileContentsHolder'. Es war auch nicht möglich, sie als com.puppycrawl.tools.checkstyle.checks.annotation.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.blocks.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.coding.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.design.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.header.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.imports.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.indentation.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.javadoc.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.metrics.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.modifier.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.naming.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.regexp.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.sizes.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.whitespace.FileContentsHolder, com.puppycrawl.tools.checkstyle.checks.FileContentsHolder, com.puppycrawl.tools.checkstyle.filefilters.FileContentsHolder, com.puppycrawl.tools.checkstyle.filters.FileContentsHolder, com.puppycrawl.tools.checkstyle.FileContentsHolder, FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.annotation.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.blocks.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.coding.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.design.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.header.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.imports.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.indentation.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.javadoc.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.metrics.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.modifier.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.naming.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.regexp.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.sizes.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.whitespace.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.checks.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.filefilters.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.filters.FileContentsHolderCheck, com.puppycrawl.tools.checkstyle.FileContentsHolderCheck zu instanziieren. Bitte prüfen Sie, dass der Klassenname als kanonischer Name angegeben wurde oder lesen Sie, wie Sie abgekürzte Namen konfigurieren: http://checkstyle.sourceforge.net/config.html#Packages. Bitte prüfen Sie auch, dass der angegebene ClassLoader des Checkers richtig konfiguriert ist.
	at com.puppycrawl.tools.checkstyle.PackageObjectFactory.createModule(PackageObjectFactory.java:208)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:166)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:186)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:459)
	... 8 more
</pre>

**Comment by lkoe** [comment]
The `FileContentsHolder` module has been removed from Checkstyle core in verion 8.2, see http://checkstyle.sourceforge.net/releasenotes.html#Release_8.2

**Comment by AlBundy33** [comment]
What does "accordingly" mean?
Here is a snippet of our checkstyle.xml
<pre>
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.2//EN" "http://www.puppycrawl.com/dtds/configuration_1_2.dtd"&gt;
&lt;module name="Checker"&gt;
	&lt;property name="severity" value="error" /&gt;
	&lt;property name="charset" value="UTF-8" /&gt;
	&lt;module name="TreeWalker"&gt;
		...
		&lt;module name="FileContentsHolder" /&gt;
		...
	&lt;/module&gt;
	...
	&lt;module name="SuppressionCommentFilter"&gt;
		&lt;property name="offCommentFormat" value="Generated By:JavaCC" /&gt;
		&lt;property name="onCommentFormat"
			value="END GENERATED CODE BY JavaCC - not applicable here, always whole files" /&gt;
	&lt;/module&gt;
&lt;/module&gt;
</pre>

If I remove the line
&lt;module name="FileContentsHolder" /&gt;
I get the next error 
<pre>
!ENTRY net.sf.eclipsecs.core 4 0 2018-01-09 17:34:13.220
!MESSAGE Checkstyle-Plugin: SuppressionCommentFilter is not allowed as a child in Checker
!STACK 0
com.puppycrawl.tools.checkstyle.api.CheckstyleException: SuppressionCommentFilter is not allowed as a child in Checker
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:484)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:186)
	at net.sf.eclipsecs.core.builder.CheckerFactory.createCheckerInternal(CheckerFactory.java:299)
	at net.sf.eclipsecs.core.builder.CheckerFactory.createChecker(CheckerFactory.java:133)
	at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:141)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.handleBuildSelection(CheckstyleBuilder.java:306)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.build(CheckstyleBuilder.java:172)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
</pre>

Is removing the FileContentsHolder the correct fix and what is the correct fix for the last exception?

**Comment by lkoe** [comment]
Yes, `SuppressionCommentFilter` is another compatibility breaking change in Checkstyle core, see http://checkstyle.sourceforge.net/releasenotes.html#Release_8.1
The module must be located as child of the `TreeWalker` module.

With "accordingly" I meant when upgrading the plugin - thus the underlying Checkstyle core version - configurations must potentially be adapted, considering backwards compatibility breaking changes in CS core.
Usually there are listed in the Checkstyle release notes.

**Comment by lkoe** [comment]
> Is removing the FileContentsHolder the correct fix and what is the correct fix for the last exception?
Ah, yes it is - for the first error you encountered

**Comment by AlBundy33** [comment]
Thanks for your help and answers. 

I thought I checked the release notes for SuppressionCommentFilter - but maybe I was on the wrong page or it was just my plan to search for it. :-) 

I've installed the plugin from marketplace and was always up-to-date afaik. 
My problems first occured after the last update of the plugins (and from oxygen 4.7.1 to 2).

Was the last update of the plugin such an major update so that the xml did not work anymore? 

Btw. do you know a schema file for the configuration - i want to be sure that all is correct now.

**Comment by lkoe** [comment]
> Was the last update of the plugin such an major update so that the xml did not work anymore?

The latest plugin version bumped the Checkstyle core version from 8.0 to 8.5, so quite some changes there.

> Btw. do you know a schema file for the configuration - i want to be sure that all is correct now.

AFAIK there is only a DTD (https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/configuration_1_3.dtd), but it only describes the structural elements.
It does't help you with figuring out the correct module placements or properties to configure, though.

**Comment by AlBundy33** [comment]
Ahh this explains the old versions i the linked release notes. :-)
I also found the dtd but hoped that you know a xsd that makes it easier to check and edit the existing xml. 

Tomorow I'll try the fixes. 

Thanks again for your help.
