### ISSUE TITLE
Oxygen.3a rejects use of java.sql

### ISSUE THREAD

**Issue by rwalkerands** [checkstyle/eclipse-cs#80]
This seems to be a problem related to Java 9. 

I just installed updates to my Eclipse, and it seems I now have Oxygen.3a, and having restarted, this is now running under a Java 9 JVM. (Hmm, maybe prior to updating Eclipse, it was running under a Java 8 JVM.)

The code I'm checking is Java 8, and I have a Java 8 JVM configured for my project.

But after the update, I now get an Error in the Problems view: "Checkstyle execution failed due to an internal error. Please check the error log for details...".

Nevertheless, I _do_ also see the correct warnings for my code in the Problems view.

When I did the update to Eclipse, I _didn't_ update the plugin from the version I was already using happily: version 8.7. So I wondered if I needed the update to the plugin, so I also updated the plugin to version 8.10.0.201805130740.

Same result.

If I try to view the properties of the Error, I get an error "The currently displayed page contains invalid values."!

My workspace `.metadata/.log` file has this at the end corresponding to the Checkstyle run:

```
!ENTRY net.sf.eclipsecs.core 4 0 2018-05-22 13:17:39.345
!MESSAGE Checkstyle-Plugin: Exception was thrown while processing /Users/rwalker/Documents/workspace/vocabs-registry/src/test/java/au/org/ands/vocabs/toolkit/test/arquillian/SubscriptionTests.java
!STACK 0
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing /Users/rwalker/Documents/workspace/vocabs-registry/src/test/java/au/org/ands/vocabs/toolkit/test/arquillian/SubscriptionTests.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:295)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:213)
        at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:158)
        at net.sf.eclipsecs.core.builder.CheckstyleBuilder.handleBuildSelection(CheckstyleBuilder.java:306)
        at net.sf.eclipsecs.core.builder.CheckstyleBuilder.build(CheckstyleBuilder.java:172)
        at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
        at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
        at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
        at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
        at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
        at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.SecurityException: Prohibited package name: java.sql
        at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:889)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1005)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:545)
        at java.base/java.net.URLClassLoader.access$100(URLClassLoader.java:83)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:453)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:447)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:446)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        at net.sf.eclipsecs.core.builder.ProjectClassLoader.loadClass(ProjectClassLoader.java:142)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:375)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.ClassResolver.safeLoad(ClassResolver.java:212)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.ClassResolver.isLoadable(ClassResolver.java:190)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.ClassResolver.resolveQualifiedName(ClassResolver.java:223)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.ClassResolver.resolveMatchingExplicitImport(ClassResolver.java:130)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.ClassResolver.resolve(ClassResolver.java:78)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractTypeAwareCheck.resolveClass(AbstractTypeAwareCheck.java:241)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractTypeAwareCheck.tryLoadClass(AbstractTypeAwareCheck.java:258)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractTypeAwareCheck$RegularClass.getClazz(AbstractTypeAwareCheck.java:470)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocMethodCheck$ExceptionInfo.getClazz(JavadocMethodCheck.java:1010)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocMethodCheck$ExceptionInfo.access$100(JavadocMethodCheck.java:968)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocMethodCheck.isInThrows(JavadocMethodCheck.java:950)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocMethodCheck.checkThrowsTags(JavadocMethodCheck.java:893)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocMethodCheck.checkComment(JavadocMethodCheck.java:494)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocMethodCheck.processAST(JavadocMethodCheck.java:354)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractTypeAwareCheck.visitToken(AbstractTypeAwareCheck.java:157)
        at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:389)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:500)
        at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:329)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:186)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:81)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:316)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:286)
        ... 16 more
```

Indeed, this test class (`SubscriptionTests`) imports `java.sql.SQLException`.

The `.metadata/.log` file then has this for the error that appeared when trying to bring up the properties of the first error:

```
!ENTRY org.eclipse.jface 4 2 2018-05-22 13:31:14.569
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.NullPointerException
        at net.sf.eclipsecs.ui.properties.marker.MarkerPropertyPage.createContents(MarkerPropertyPage.java:61)
        at org.eclipse.jface.preference.PreferencePage.createControl(PreferencePage.java:241)
        at org.eclipse.jface.preference.PreferenceDialog.createPageControl(PreferenceDialog.java:1426)
        at org.eclipse.jface.preference.PreferenceDialog$8.run(PreferenceDialog.java:1193)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
        at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
        at org.eclipse.jface.preference.PreferenceDialog.showPage(PreferenceDialog.java:1185)
        at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.showPage(FilteredPreferenceDialog.java:591)
        at org.eclipse.jface.preference.PreferenceDialog$5.lambda$0(PreferenceDialog.java:657)
        at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
        at org.eclipse.jface.preference.PreferenceDialog$5.selectionChanged(PreferenceDialog.java:654)
        at org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:872)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
        at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
        at org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:869)
        at org.eclipse.jface.viewers.StructuredViewer.setSelection(StructuredViewer.java:1718)
        at org.eclipse.jface.viewers.TreeViewer.setSelection(TreeViewer.java:1075)
        at org.eclipse.jface.preference.PreferenceDialog.selectSavedItem(PreferenceDialog.java:987)
        at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.selectSavedItem(FilteredPreferenceDialog.java:639)
        at org.eclipse.jface.preference.PreferenceDialog.lambda$0(PreferenceDialog.java:347)
        at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
        at org.eclipse.jface.preference.PreferenceDialog.createContents(PreferenceDialog.java:344)

etc.
```

If I quit Eclipse, move the Java 9 JVM out of the way, and restart, then Eclipse is running under a Java 8 JVM again, and the SecurityException error does not occur.

I also do command-line builds using Ant. Running the checkstyle task under Ant with a Java 9 JVM doesn't (seem to) produce the SecurityException: at least, if it's being generated, I don't see it.

**Comment by rwalkerands** [comment]
This page may (or may not) be relevant: https://stackoverflow.com/questions/46494112/classloaders-hierarchy-in-java-9/46494286

**Comment by lkoe** [comment]
I think this happens on Java 9 and greater due to Project Jigsaw.
Checkstyle core does some classloading on its own for certain checks (IllegalType, JavadocMethod). Due to access limitations imposed by Jigsaw, certain classes can't be loaded anymore.
To suppress these issues you can try to use the `suppressLoadErrors` property of the aforementioned checks.

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java  unlikely to cause class load problems.

https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java#L50 is AbstractTypeAwareCheck so it could cause problem as it try to use classload.

Please try to deactivate JavadocMethodCheck and let us know.

**Comment by rwalkerands** [comment]
I already had this in my config:

```
    <module name="JavadocMethod">
      <property name="suppressLoadErrors" value="true"/>
    </module>
```

So I get the error with JDK 9, even with the `suppressLoadErrors` setting.

I commented out this check and restarted Eclipse. Now, the error does not occur.

**Comment by romani** [comment]
```
Caused by: java.lang.SecurityException: Prohibited package name: java.sql
....
        at com.puppycrawl.tools.checkstyle.checks.javadoc.ClassResolver.resolve(ClassResolver.java:78)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractTypeAwareCheck.resolveClass(AbstractTypeAwareCheck.java:241)
```

Looks like we need to catch all exceptions at https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractTypeAwareCheck.java#L237

**Comment by romani** [comment]
Moved to https://github.com/checkstyle/checkstyle/issues/6606
